let A=["","Aston Martin Vantage","Porsche 718 Cayman","BMW X1","Lamborghini Huracán EVO variant","BMW M4 Coupe","Lamborghini Aventador","Nissan GT-R","Lamborghini Veneno","Mercedes-Maybach S-Class","Mercedes-Maybach GLS 600","Audi R8 V10","Chevrolet Corvette C","ROLLS-ROYCE GHOST","Ferrari 488 GTB","Lamborghini Aventador","McLaren 765LT",""];

let B=[[""]
,[" Sports Car / Luxury Sports Coupe"," Vantage","First introduced: 2005 Latest generation: 2024 – Present","Around ₹3.99 Crore (ex-showroom)","325 km/h","Engine Type: 4.0-Litre Twin-Turbocharged V8 Petrol Engine","Power Output: about 665 HP (PS)","Torque: 800 Nm","Transmission: 8-speed automatic gearbox","The Aston Martin Vantage is a high-performance British sports car known for its aggressive design, powerful engine, and luxury interior. The latest version features a redesigned front grille, advanced aerodynamics, and modern technology such as a digital infotainment system and driver-assistance features. It is designed to deliver a balance of luxury, speed, and precise handling."]
,["Sports Car / Luxury Coupe"," 718 Cayman","Introduced as the 718 generation in 2016 – Present","Around ₹85 lakh – ₹1.6 crore (ex-showroom)","about 275 km/h","Engine Type: 2.0-L Turbocharged Flat-4 (mid-engine)","Displacement: 1988 cc","Power: 300 hp","Torque: 380 Nm","The Porsche 718 Cayman is a two-seat mid-engine sports car known for its excellent balance, precise handling, and strong performance. The mid-engine layout improves weight distribution, making it one of the best driver-focused sports cars in its class. It is often considered Porsche’s entry-level sports coupe, competing with cars like the BMW M2, Toyota Supra, and Alpine A110."]
,["Luxury Compact SUV","X1","First introduced: 2009 Latest generation: 2023 – Present (U11 generation)","Around ₹49 lakh – ₹52 lakh (ex-showroom)","Approx. 222 km/h","Engine Type: 1.5-L Turbocharged 3-Cylinder Petrol Engine","Displacement: 1499 cc","Power: 136 hp","Torque: 230 Nm","The BMW X1 is a luxury compact SUV designed for comfort, performance, and practicality. It is one of BMW’s most popular entry-level SUVs and is known for its premium interior, advanced technology, and efficient engines. The latest model features a large curved display, improved cabin space, and modern driver-assistance systems."]
,["Supercar / Sports Car","Huracán EVO","2019 – Present","₹3.22 – ₹3.73 Crore","325 km/h","Engine Type: 5.2-Litre V10 Petrol Engine","Power: 640 HP","Torque: 600 Nm","Transmission: 7-speed automatic","The Huracán EVO is known for its aggressive design and high performance, reaching 0–100 km/h in about 2.9 seconds"]
,["High-Performance Sports Coupe","M4 Coupe","First introduced: 2014 Current generation: 2021 – Present (G82 generation)","Around ₹1.53 Crore – ₹1.89 Crore (ex-showroom)","250 km/h ","3.0-Litre Twin-Turbocharged Inline-6 Petrol Engine","Displacement: 2993 cc","Power: 510 hp (Competition variant)","Torque: 650 Nm","The BMW M4 Coupe is a high-performance sports car developed by BMW’s M division. It is known for its aggressive design, powerful turbocharged engine, and track-focused driving dynamics. The car features advanced technologies such as adaptive suspension, high-performance brakes, and multiple driving modes for both road and track performance."]
,[" Supercar / Hypercar","Aventador","2011 – 2022 (production ended and replaced by the Revuelto)","Around ₹6.25 Crore – ₹9 Crore (ex-showroom)","350 km/h","6.5-Litre Naturally Aspirated V12 Petrol Engine","Displacement: 6498 cc","Power: 770 hp (Aventador Ultimae)","Torque: 720 Nm","The Lamborghini Aventador is one of Lamborghini’s most iconic supercars, known for its aggressive design, scissor doors, and powerful V12 engine. It was Lamborghini’s flagship model for more than a decade and became famous for its extreme performance and futuristic styling. The Aventador uses a carbon-fiber monocoque chassis, making the car lightweight yet very strong."]
,["High-Performance Sports Car / Supercar","GT-R (R35)","Current generation introduced: 2007 – Present","Around ₹2.12 Crore (ex-showroom)","315 km/h","3.8-Litre Twin-Turbocharged V6 Petrol Engine","Displacement: 3799 cc","Power: 565 hp (standard GT-R)","Torque: 637 Nm","The Nissan GT-R, often called “Godzilla”, is one of the most famous high-performance sports cars in the world. It is known for its advanced all-wheel-drive system, powerful twin-turbo engine, and incredible acceleration. The GT-R is capable of competing with much more expensive supercars while maintaining relatively lower pricing compared to brands like Ferrari or Lamborghini."]
,["Hypercar / Limited Edition Supercar","Veneno","2013 – 2014","Around ₹64 Crore (estimated in India)","355 km/h","6.5-Litre Naturally Aspirated V12 Petrol Engine","Displacement: 6498 cc","Power: 750 hp","Torque: 690 Nm","The Lamborghini Veneno is an extremely rare limited-edition hypercar built to celebrate Lamborghini’s 50th anniversary. Only a few units were produced, making it one of the most exclusive and expensive Lamborghinis ever made. It features aggressive aerodynamics, a lightweight carbon-fiber body, and a powerful V12 engine capable of delivering extreme performance."]
,["Ultra-Luxury Sedan","Mercedes-Maybach S-Class","2021 – Present","Around ₹2.7 Crore – ₹3.5 Crore (ex-showroom) in India","250 km/h (electronically limited)","4.0-Litre Twin-Turbocharged V8 Petrol Engine with Mild Hybrid (EQ Boost)","Displacement: 3982 cc","Power: 503 hp","Torque: 700 Nm","The Mercedes-Maybach S-Class is an ultra-luxury sedan designed for maximum comfort, advanced technology, and premium craftsmanship. It offers features like reclining rear seats, executive rear cabin, high-end materials, and advanced driver assistance systems. The car combines powerful performance with exceptional ride comfort, making it one of the most luxurious sedans in the world."]
,["Ultra-Luxury SUV","Mercedes-Maybach GLS 600","2020 – Present","Around ₹3.35 Crore (ex-showroom) in India","250 km/h (electronically limited)","4.0-Litre Twin-Turbocharged V8 Petrol Engine with EQ Boost Mild Hybrid","Displacement: 3982 cc","Power: 557 hp","Torque: 730 Nm","The Mercedes-Maybach GLS 600 is an ultra-luxury SUV that combines the comfort of the Maybach brand with the practicality of a large SUV. It offers an extremely luxurious rear cabin with reclining seats, premium materials, advanced technology, and a smooth air suspension system, making it one of the most luxurious SUVs in the world."]
,["Supercar / High-Performance Sports Car","Audi R8 V10","2015 – 2023","Around ₹2.72 Crore – ₹3.20 Crore (ex-showroom) in India","331 km/h","5.2-Litre Naturally Aspirated V10 Petrol Engine","Displacement: 5204 cc","Power: 602 hp (R8 V10 Performance)","Torque: 560 Nm","The Audi R8 V10 is a high-performance supercar known for its naturally aspirated V10 engine, sharp handling, and everyday usability compared to many other supercars. It features Audi’s Quattro all-wheel-drive system, advanced aerodynamics, and a driver-focused interior, making it one of the most iconic performance cars produced by Audi."]
,["Sports Car / Supercar","Chevrolet Corvette C8","2020 – Present","Around ₹1.20 Crore – ₹1.50 Crore (estimated price in India if imported)","312 km/h","6.2-Litre Naturally Aspirated V8 Petrol Engine","Displacement: 6162 cc","Power: 495 hp","Torque: 637 Nm","The Chevrolet Corvette C8 is the first mid-engine Corvette ever produced, marking a major change in the Corvette lineup. It offers supercar-level performance with a powerful V8 engine, advanced aerodynamics, and a driver-focused cockpit. The C8 is known for delivering exceptional performance at a comparatively affordable price compared to many European supercars."]
,["Ultra-Luxury Sedan","Rolls-Royce Ghost","2020 – Present","Around ₹6.95 Crore – ₹7.95 Crore (ex-showroom) in India","250 km/h (electronically limited)","6.75-Litre Twin-Turbocharged V12 Petrol Engine","Displacement: 6750 cc","Power: 563 hp","Torque: 850 Nm","The Rolls-Royce Ghost is a luxury sedan known for its exceptional comfort, handcrafted interior, and smooth performance. It features advanced engineering with a powerful V12 engine and the famous 'Magic Carpet Ride' suspension system, providing one of the smoothest driving experiences. The Ghost represents elegance, prestige, and modern luxury in the Rolls-Royce lineup."]
,["Supercar / High-Performance Sports Car","Ferrari 488 GTB","2015 – 2019","Around ₹3.88 Crore (ex-showroom) in India","330 km/h","3.9-Litre Twin-Turbocharged V8 Petrol Engine","Displacement: 3902 cc","Power: 661 hp","Torque: 760 Nm","The Ferrari 488 GTB is a high-performance mid-engine supercar known for its powerful twin-turbo V8 engine, sharp handling, and advanced aerodynamics. It was designed as the successor to the Ferrari 458 Italia and delivers exceptional acceleration, reaching 0–100 km/h in about 3 seconds while offering the classic Ferrari driving experience."]
,["Supercar / Hypercar","Lamborghini Aventador","2011 – 2022","Around ₹6.25 Crore – ₹9 Crore (ex-showroom) in India","350 km/h","6.5-Litre Naturally Aspirated V12 Petrol Engine","Displacement: 6498 cc","Power: 770 hp (Aventador Ultimae)","Torque: 720 Nm","The Lamborghini Aventador is one of Lamborghini’s most iconic supercars, known for its aggressive design, scissor doors, and powerful V12 engine. It served as Lamborghini’s flagship model for more than a decade and features a lightweight carbon-fiber monocoque chassis, advanced aerodynamics, and extreme performance capabilities."]
,["Supercar / High-Performance Sports Car","McLaren 765LT","2020 – 2023","Around ₹12 Crore (estimated price in India, ex-showroom)","330 km/h","4.0-Litre Twin-Turbocharged V8 Petrol Engine","Displacement: 3994 cc","Power: 755 hp","Torque: 800 Nm","The McLaren 765LT is an extreme lightweight version of the McLaren 720S designed for track-focused performance. It features aggressive aerodynamics, extensive carbon-fiber components, and a powerful twin-turbo V8 engine. The 765LT delivers incredible acceleration, reaching 0–100 km/h in about 2.8 seconds, making it one of the fastest and most performance-oriented cars produced by McLaren."]]
function sendImage(imgId,v) {
    let imgSrc = document.getElementById(imgId).src;
    localStorage.setItem("selectedCar", imgSrc);
    localStorage.setItem("index",v);
    window.open("Details.html", "_blank");
   
}


window.onload = function() {
    let imgSrc = localStorage.getItem("selectedCar");
    let index=this.localStorage.getItem("index");
    if (imgSrc) {
        let img = document.createElement("img");
        img.src = imgSrc;
        img.alt = "Selected Car";
        document.getElementById("output").appendChild(img);
    }
    if(index)
    {
        document.getElementById("name").innerText=A[index];
        document.getElementById("ca").innerText=B[index][0];
        document.getElementById("mo").innerText=B[index][1];
        document.getElementById("md").innerText=B[index][2];
        document.getElementById("pi").innerText=B[index][3];
        document.getElementById("speed").innerText=B[index][4];
        document.getElementById("li1").innerText=B[index][5];
        document.getElementById("li2").innerText=B[index][6];
        document.getElementById("li3").innerText=B[index][7];
        document.getElementById("li4").innerText=B[index][8];
        document.getElementById("about").innerText=B[index][9];
    }
};